package org.example.wizardpages;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.example.model.BagitParam;
import org.example.model.BagitParamModel;
import org.example.wizard.AbstractWizardPage;

import javax.swing.*;
import java.awt.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;

public class BagitInfoPage extends AbstractWizardPage {
    private final AbstractWizardPage nextPage = new FinalPage();
    private final BagitParamModel bagitParamModel = new BagitParamModel();

    private JTable ParameterTable;
    private JScrollPane ScrollPanel;
    private JPanel MainPanel;

    public BagitInfoPage() {
        $$$setupUI$$$();

        String rootPath = Thread.currentThread().getContextClassLoader().getResource("").getPath();
        String appConfigPath = rootPath + "parameter.properties";

        Properties appProps = new Properties();
        try {
            FileInputStream input = new FileInputStream(appConfigPath);
            appProps.load(new InputStreamReader(input));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        List<String> parameterList = Arrays.asList(appProps.getProperty("Parameter").split(","));

        parameterList.forEach(parameter -> bagitParamModel.addParameter(new BagitParam(parameter, appProps.getProperty(parameter, ""))));


        ParameterTable.setModel(bagitParamModel);
        add(MainPanel);

    }

    @Override
    protected AbstractWizardPage getNextPage() {
        return this.nextPage;
    }

    @Override
    protected boolean isCancelAllowed() {
        return true;
    }

    @Override
    protected boolean isPreviousAllowed() {
        return true;
    }

    @Override
    protected boolean isNextAllowed() {
        return true;
    }

    @Override
    protected boolean isFinishAllowed() {
        return false;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        ScrollPanel = new JScrollPane();
        MainPanel.add(ScrollPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ParameterTable = new JTable();
        ScrollPanel.setViewportView(ParameterTable);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Testtext weofnwoefhwoefhwoefh");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
